defmodule Rbtz.CredoChecks do
  @moduledoc """
  Helpers for wiring the Tiny Robots Credo checks into your `.credo.exs`.

  `all/0` returns every check in this library as a `{check_module, opts}` tuple,
  ready to append to the `enabled:` list in your `.credo.exs`:

      checks: %{
        enabled:
          [
            # ...your Credo built-in checks...
          ] ++ Rbtz.CredoChecks.all()
      }

  The list is generated by discovering every check module in the library, so it
  stays in sync automatically as checks are added — there's nothing to
  hand-maintain.

  ## Customising and disabling checks

  Use `all_replacing/1` to override a check's options. Each replacement is matched
  by module name and swaps in the given options:

      Rbtz.CredoChecks.all_replacing([
        {Rbtz.CredoChecks.Readability.SnakeCaseVariableNumbering,
         exclude: ["utf8", "ipv4", "ipv6"]}
      ])

  Pass `false` as the options to disable a check. Credo treats `{check, false}`
  as disabled, so the check stays in the list but is turned off:

      Rbtz.CredoChecks.all_replacing([
        {Rbtz.CredoChecks.Design.PreferLogsterInLib, false}
      ])

  A replacement naming a module that isn't one of this library's checks raises an
  `ArgumentError`, so typos and stale config surface immediately.
  """

  @doc """
  Returns all Tiny Robots Credo checks as `{check_module, []}` tuples.

  See `all_replacing/1` to customise or disable individual checks.
  """
  @spec all() :: [{module(), []}]
  def all, do: build_checks([])

  @doc """
  Returns all Tiny Robots Credo checks, replacing the options of the ones named
  in `replacements`.

  `replacements` is a list of `{check_module, opts}` tuples. For each, the
  matching check's default options are replaced with `opts` — a keyword list, or
  `false` to disable the check. Replacing a module that isn't part of this
  library raises `ArgumentError`.
  """
  @spec all_replacing([{module(), keyword() | false}]) :: [{module(), keyword() | false}]
  def all_replacing(replacements), do: build_checks(replacements)

  defp build_checks(replacements) do
    defaults = check_modules()
    overrides = Map.new(replacements)

    case Map.keys(overrides) -- defaults do
      [] ->
        :ok

      unknown ->
        raise ArgumentError,
              "unknown check(s) in replacements: " <> Enum.map_join(unknown, ", ", &inspect/1)
    end

    Enum.map(defaults, fn module -> {module, Map.get(overrides, module, [])} end)
  end

  defp check_modules do
    # `Application.spec/2` only returns the module list once the app is loaded,
    # which isn't guaranteed when Credo evaluates `.credo.exs`. Loading is cheap
    # and idempotent (it just reads the `.app` file; it does not start the app).
    _ = Application.load(:rbtz_credo_checks)

    :rbtz_credo_checks
    |> Application.spec(:modules)
    |> List.wrap()
    |> Enum.filter(&credo_check?/1)
    |> Enum.sort()
  end

  defp credo_check?(module) do
    Code.ensure_loaded?(module) and Credo.Check in declared_behaviours(module)
  end

  defp declared_behaviours(module) do
    module.module_info(:attributes)
    |> Keyword.get_values(:behaviour)
    |> List.flatten()
  end
end
